### ISSUE TITLE
SOLR selection misses one Lucene file out

### ISSUE THREAD

**Issue by thomassimm** [reyrahadian/Sitecore-Server-Role-Checker#1]
When selecting Search Engine Provider - SOLR and analyze. There seems to be one file left over which stops Sitecore from functioning.

Location - Website\App_Config\Include\Social
File Name - Sitecore.Social.Lucene.Index.Analytics.Facebook.config
Version - Sitecore 8.2 Update 2

This file is not in the list.
Don't know if this is your issue or Sitecores Excel Sheet?

**Comment by reyrahadian** [comment]
I checked the latest Sitecore excel sheet, and that file is not being included in the config spreadsheet which seems to be cause of the issue.

Should be a quick csv and xsl update to fix on my end.

thanks for reporting
